In [1]:
import numpy as np

In [2]:
l = [3,6,32,7]
arr = np.array(l)

In [3]:
arr

array([ 3,  6, 32,  7])

In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [5]:
arr1[0,1]

2

In [6]:
arr[0]

3

In [7]:
arr1[0]

array([1, 2, 3])

In [8]:
arr1.shape

(2, 3)

In [9]:
arr.shape

(4,)

In [10]:
arr.dtype

dtype('int64')

In [11]:
arr[1]=45


In [12]:
arr


array([ 3, 45, 32,  7])

# ***Conversion from other Python structures ***

In [13]:
import numpy as np

In [14]:
lstarr=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [15]:
lstarr

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [16]:
lstarr.dtype

dtype('int64')

In [17]:
lstarr.shape

(3, 3)

In [18]:
lstarr.size

9

# Intrinsic NumPy array creation functions ******

In [19]:
zeros = np.zeros((2,5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [22]:
zeros.shape

(2, 5)

In [23]:
rng = np.arange(15)

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
lspace = np.linspace(1,4,4)

In [26]:
lspace

array([1., 2., 3., 4.])