In [1]:
import numpy as np

In [2]:
l = [3,6,32,7]
arr = np.array(l)

In [3]:
arr

array([ 3,  6, 32,  7])

In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [5]:
arr1[0,1]

2

In [6]:
arr[0]

3

In [7]:
arr1[0]

array([1, 2, 3])

In [8]:
arr1.shape

(2, 3)

In [9]:
arr.shape

(4,)

In [10]:
arr.dtype

dtype('int64')

In [11]:
arr[1]=45


In [12]:
arr


array([ 3, 45, 32,  7])

# ***Conversion from other Python structures ***

In [13]:
import numpy as np

In [14]:
lstarr=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [15]:
lstarr

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [16]:
lstarr.dtype

dtype('int64')

In [17]:
lstarr.shape

(3, 3)

In [18]:
lstarr.size

9

# Intrinsic NumPy array creation functions ******

In [19]:
zeros = np.zeros((2,5))

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [22]:
zeros.shape

(2, 5)

In [23]:
rng = np.arange(15)

In [24]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
lspace = np.linspace(1,4,4)

In [26]:
lspace

array([1., 2., 3., 4.])

In [27]:
emp = np.empty((4,6))

In [28]:
emp

array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

In [29]:
emp_like = np.empty_like(lspace)

In [30]:
emp_like

array([1., 2., 3., 4.])

In [31]:
ide = np.identity(5)

In [32]:
ide

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
ide.shape

(5, 5)

In [34]:
arr2 = np.arange(99)

In [35]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [36]:
arr2.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [37]:
arr2.reshape(33,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [38]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [39]:
arr2 = arr2.reshape(3,33)

In [40]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [41]:
arr2.shape

(3, 33)

In [42]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [44]:
arr2 = arr2.ravel()

In [45]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [46]:
arr2.shape

(99,)

In [47]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [48]:
arr3 = np.array(x)

In [49]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
arr3.sum(axis=0)

array([12, 15, 18])

In [51]:
arr3.sum(axis=1)

array([ 6, 15, 24])

In [52]:
arr3.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [53]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr3.flat

In [55]:
for item in arr3.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [56]:
arr3.ndim

2

In [57]:
arr3.size

9

In [58]:
arr3.nbytes

72

In [59]:
arr3.dtype

dtype('int64')

In [60]:
arr3.dtype('int8')

TypeError: 'numpy.dtypes.Int64DType' object is not callable

In [61]:
one = np.array([1,3,4,634,2])

In [62]:
one.argmax()

3

In [63]:
one.argmin()

0

In [64]:
one.argsort()

array([0, 4, 1, 2, 3])

In [65]:
one.dtype

dtype('int64')

In [66]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
arr3.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [68]:
arr3.argmin()

0

In [69]:
arr3.argmax()

8

In [70]:
arr3.argmax(axis=0)

array([2, 2, 2])

In [71]:
arr3.argmin(axis=0)

array([0, 0, 0])

In [72]:
arr3.argmin(axis=1)

array([0, 0, 0])

In [73]:
arr3.argmax(axis=1)

array([2, 2, 2])

In [74]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr4 = np.array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
arr3 + arr4

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [77]:
arr4 = np.array(arr3)

In [78]:
arr4

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
arr3 + arr4

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [80]:
arr3 * arr4

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [81]:
arr3 / arr4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [82]:
arr3 - arr4

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [83]:
np.sqrt(arr3)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [84]:
arr3.sum()

45

In [85]:
arr3.max()

9

In [86]:
arr3.min()

1

In [87]:
np.where(arr3>5)

(array([1, 2, 2, 2]), array([2, 0, 1, 2]))

In [88]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
np.count_nonzero(arr3)

9

In [90]:
np.nonzero(arr3)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))

In [91]:
arr3[1,2]=0

In [92]:
np.nonzero(arr3)

(array([0, 0, 0, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 0, 1, 2]))